"""Initial schema setup

Revision ID: 2b3252908512
Revises: 
Create Date: 2026-09-27 20:45:45.378081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3252908512'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_medication_logs_scheduled_date'), 'medication_logs', ['scheduled_date'], unique=False)
    op.alter_column('medicines', 'medicine_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Tablet'"))
    op.alter_column('medicines', 'reminder_times',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_medicines_patient_id'), 'medicines', ['patient_id'], unique=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'unread'"))
    op.create_foreign_key(None, 'notifications', 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'medicine_schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'unread'"))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_medicines_patient_id'), table_name='medicines')
    op.alter_column('medicines', 'reminder_times',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('medicines', 'medicine_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Tablet'"))
    op.drop_index(op.f('ix_medication_logs_scheduled_date'), table_name='medication_logs')
    # ### end Alembic commands ###
